<?php

function menu_icons_list() {
  return array(
    '672' => 'about-us.png',
    'default' => 'about-us.png',
    '662' => 'patients.png',
    '670' => 'physitions.png',
    '676' => 'specialty.png',
    '2265' => 'careers.png',

  );
}
function menu_icons_titles() {
  return array(
    'About_us_Submenu' => 'about-us.png',
    'default' => 'about-us.png',
    'Patients_Submenu' => 'patients.png',
    'Physician_Submenu' => 'physitions.png',
    '676' => 'specialty.png',
   
  );
}